{
 "title": "Loki:AccessLogs",
 "description": "Loki dashboards for promtail metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "datasource", "label": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "HTTP_status_200",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"\\\\s200\\\\s\" [15m] )"
    }
   ]
  },
  {
   "title": "HTTP_status_302",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"\\\\s302\\\\s\" [15m] )"
    }
   ]
  },
  {
   "title": "HTTP_status_404",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"\\\\s404\\\\s\" [15m])"
    }
   ]
  },
  {
   "title": "200_Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"\\\\s200\\\\s\""
    }
   ]
  },
  {
   "title": "300_Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"\\\\s30[0-9]\\\\s\""
    }
   ]
  },
  {
   "title": "400_Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"\\\\s40[0-9]\\\\s\""
    }
   ]
  },
  {
   "title": "500_Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"\\\\s50[0-9]\\\\s\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}