{
 "title": "Telegraf:SystemResources",
 "description": "InfluxDB dashboards for telegraf metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"${buckets}\", tag: \"host\")"
   },
   { "name": "buckets", "query": "buckets()" }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"uptime\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"load5\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"zombies\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"running\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"total_threads\"\r\n)",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "blocked",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"blocked\"\r\n)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "dead",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"dead\"\r\n)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "idle",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"idle\"\r\n)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "paging",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"paging\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "processes_unknown",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"unknown\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Load averages1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"load1\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "CPU usage_system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"cpu\" and\r\n  r._field == \"usage_system\" and\r\n  r.cpu == \"cpu-total\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Load averages5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"load5\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "CPU usage_user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"cpu\" and\r\n  r._field == \"usage_user\" and\r\n  r.cpu == \"cpu-total\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Load averages15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"load15\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"cpu\" and\r\n  r._field == \"usage_softirq\" and\r\n  r.cpu == \"cpu-total\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory available",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"mem\" and\r\n  r._field == \"available\"\r\n)"
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kernel\" and\r\n  r._field == \"context_switches\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kernel\" and\r\n  r._field == \"processes_forked\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Entropy avail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kernel\" and\r\n  r._field == \"entropy_avail\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Interrupts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_irq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "irq" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrupts",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kernel\" and\r\n  r._field == \"interrupts\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Per-cpu usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "CPU Idle for $cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "repeat": "cpu",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"cpu\" and\r\n  r._field == \"usage_idle\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Conntrack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Netstat tcp_established",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$server: current",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conntrack",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"netstat\" and\r\n  r._field == \"tcp_established\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "ip_conntrack_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$server: maximum",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conntrack",
     "select": [
      [
       { "params": [ "ip_conntrack_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Network stack (TCP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"tcp_maxconn\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "TCP aborts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"tcp_estabresets\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "TCP handshake issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"tcp_passiveopens\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "TCP SYN cookies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"netstat\" and\r\n  r._field == \"tcp_syn_recv\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "TcpExtSyncookiesFailed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "received",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"netstat\" and\r\n  r._field == \"tcp_syn_sent\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "TcpExtSyncookiesRecv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "TcpExtSyncookiesSent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "ICMP packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "out echos",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"packets_sent\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "IcmpOutEchos" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "in echo responses",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpInEchoReps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "out echo responses",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpOutEchoReps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "ICMP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"icmp_inerrors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "IcmpInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "out errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"icmp_outerrors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "IcmpOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "checksum errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpInCsumErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "IPv4 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"ip_inaddrerrors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "alias": "in discards",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "out discards",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "in hdr errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpInHdrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "in addr errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpInAddrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "out no routes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpOutNoRoutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "in unknown protocol",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpInUnknownProtos" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "IPv6 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in discards",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6InDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "out discards",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6OutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "in hdr errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6InHdrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "in addr errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6InAddrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "out no routes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6OutNoRoutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "in unknown protocol",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6InUnknownProtos" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"ip_inhdrerrors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Network stack (UDP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "UDP datagrams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"udp_outdatagrams\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "UDP buffer errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Send buffer errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"udp_rcvbuferrors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "UdpSndbufErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Receive buffer errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"udp_sndbuferrors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "UdpRcvbufErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "checksum errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"udp_inerrors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "UdpInCsumErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "in errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "no ports",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "repeat": "netif"
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"bytes_recv\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"bytes_sent\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"packets_recv\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"packets_sent\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Network drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "pps", "label": "Drops per second" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"drop_in\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"drop_out\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"err_in\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"net\" and\r\n  r._field == \"err_out\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"swap\" and\r\n  r._field == \"in\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"swap\" and\r\n  r._field == \"out\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"swap\" and\r\n  r._field == \"used\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"swap\" and\r\n  r._field == \"total\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Disk IOPS for /dev/$disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 }, "repeat": "disk" },
  {
   "title": "Disk I/O reads  requests /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"diskio\" and\r\n  r._field == \"reads\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk I/O writes requests /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"diskio\" and\r\n  r._field == \"writes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk I/O read  bytes /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"diskio\" and\r\n  r._field == \"read_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk I/O write bytes  /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 155 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"diskio\" and\r\n  r._field == \"write_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"diskio\" and\r\n  r._field == \"read_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk I/O read time  /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"diskio\" and\r\n  r._field == \"read_time\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"diskio\" and\r\n  r._field == \"write_time\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk I/O  write time  /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"diskio\" and\r\n  r._field == \"write_time\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 },
   "repeat": "mountpoint"
  },
  {
   "title": "Disk usage for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"disk\" and\r\n  r._field == \"free\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk inodes for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"disk\" and\r\n  r._field == \"inodes_free\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  }
 ]
}