{
 "title": "Loki:SystemLogs",
 "description": "Loki dashboards for promtail metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {}
   },
   { "name": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "info",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time( {node=~\"$node\"} |~ \"info\" [15m])"
    }
   ]
  },
  {
   "title": "warning",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count_over_time( {node=~\"$node\"} |~ \"warning\" [15m])"
    }
   ]
  },
  {
   "title": "alert",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time( {node=~\"$node\"} |~ \"alert\" [15m])"
    }
   ]
  },
  {
   "title": "error",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count_over_time( {node=~\"$node\"} |~ \"error\" [15m])"
    }
   ]
  },
  {
   "title": "crit",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{node=~\"$node\"} |~ \"crit\""
    }
   ]
  },
  {
   "title": "info_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{node=~\"$node\"} |~ \"info\""
    }
   ]
  },
  {
   "title": "warning_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{node=~\"$node\"} |~ \"warning\""
    }
   ]
  },
  {
   "title": "alart_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{node=~\"$node\"} |~ \"alert\""
    }
   ]
  },
  {
   "title": "error_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{node=~\"$node\"} |~ \"error\""
    }
   ]
  },
  {
   "title": "crit_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{node=\"$node\"} |~ \"crit\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "{node=~\"$node\"}"
    }
   ]
  }
 ]
}